#!/usr/bin/env python3
"""
Regenerate asm/header.s from a local frontbin.elf.

The .header segment (file offset 0x0..0x1000) is raw ELF32/MIPS header
structure plus zero padding -- not decompiled source -- so it's captured
once as a byte dump rather than reconstructed from C/asm. This script
regenerates asm/header.s from YOUR OWN legally-obtained frontbin.elf, the
same pattern the project already uses for the retail ELF itself (verified
by sha1 in frontbin.splat.yaml, never committed).

Emits `.byte` directives rather than `.incbin`: this project's SN Systems
ee-as.exe build has no working .incbin support (confirmed: "Unknown
pseudo-op" + a bfd assertion fail in elf32-mips.c), so the bytes are baked
directly into the assembly source instead.

Run from the project root:
    python extract_header.py
"""
import hashlib
from pathlib import Path

ELF_PATH = Path("frontbin.elf")
OUT_PATH = Path("asm/header.s")
HEADER_SIZE = 0x1000
EXPECTED_SHA1 = "3BC94EE895E4B4AF9B5602A229AF599C1103B542"


def main():
    if not ELF_PATH.exists():
        raise SystemExit(f"{ELF_PATH} not found -- supply your own legally-obtained copy")

    data = ELF_PATH.read_bytes()
    actual_sha1 = hashlib.sha1(data).hexdigest().upper()
    if actual_sha1 != EXPECTED_SHA1:
        print(
            f"WARNING: {ELF_PATH} sha1 mismatch\n"
            f"  expected: {EXPECTED_SHA1}\n"
            f"  actual:   {actual_sha1}\n"
            f"  (continuing anyway -- header bytes may not match this project's assumptions)"
        )

    header = data[:HEADER_SIZE]

    lines = [
        "/* header.s -- raw ELF header + program-header blob for frontbin.elf's",
        " * .header segment (file offset 0x0..0x1000). Auto-generated by",
        " * extract_header.py from your local frontbin.elf -- do not hand-edit,",
        " * and do not commit this file (it's derived from copyrighted retail",
        " * data; contributors regenerate it locally, same as frontbin.elf).",
        " *",
        " * Emitted as .byte directives, not .incbin: this project's ee-as.exe",
        " * build has no working .incbin support.",
        " */",
        ".section .data",
        ".align 4",
    ]
    for i in range(0, len(header), 16):
        chunk = header[i : i + 16]
        byte_list = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    .byte {byte_list}")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(header)} bytes ({len(lines) - 11} .byte lines) to {OUT_PATH}")


if __name__ == "__main__":
    main()
